Updated Dockerfile and guide
aarhusstadsarkiv/convertool pull request #410
Opened 2022-02-18 13:51 UTC by iSplasher

This PR updates the Dockerfile to be based on a specific python version and makes it so that poetry will not use virtualenvs inside the container.

Support for docker-compose has also been added.

2022-02-18 14:20 UTC, lurilandi requested changes

2022-02-18 14:20 UTC, lurilandi commented on docker_how_to_run.md
> +You can rerun the command above while supplying `-v (path/to/files):/usr/data`, change `(path/to/files)` to the absolute path pointing to your dataset on your local machine.
```suggestion
You can rerun the command above while supplying `-v (path/to/files):/usr/data`, change `(path/to/files)` to the absolute path pointing to your dataset on your local machine.

The resulting docker-compose command will be `docker-compose -v  (path/to/files):/usr/data run --rm convertool`

```

2022-02-21 08:33 UTC, lurilandi requested changes

2022-02-21 08:33 UTC, lurilandi commented on docker_how_to_run.md
> +There are 2 general solutions available when actively developing using docker.
```suggestion
There are 2 general solutions available when developing using docker.
```

2022-02-21 08:33 UTC, lurilandi commented on docker_how_to_run.md
> +The first time you run these commands will likely take a long time to complete because dependencies need to be built and installed.
Er dette korrekt? Du køre jo ikke nogen commands før du bygger billedet. Så "the first time you run these commands will likely take a long time" giver ikke mening, da du først bygger billedet og derefter starter en container baseret på billedet.

2022-02-21 08:33 UTC, lurilandi commented on docker_how_to_run.md
> +#### 1. Using `docker`
```suggestion
#### 1. Using the `docker` command.
```

2022-02-21 08:33 UTC, lurilandi commented on docker_how_to_run.md
> +With a terminal inside the convertool folder, build the image with `docker build -t convertool --rm .`
Forklar eventuelt hvad commanden gør. I.e. -t giver den et tag. Hvad sletter --rm og hvad er `.` (konteksten der gives til docker build).

2022-02-21 08:33 UTC, lurilandi commented on docker_how_to_run.md
> +This can be done with the `-v` option which takes an argument of the form `SOURCE:MOUNTPOINT`.
Giver det mening, at `-v` optionen forklares her, når den allerede bruges ovenover?

2022-02-21 08:33 UTC, lurilandi commented on tests/test_data/AARS.TEST/docCollection_test/test.html
> +<!DOCTYPE html>
This file was probably not intended to be a part of this pull request.

2022-02-23 12:30 UTC, iSplasher commented on docker_how_to_run.md
> +The first time you run these commands will likely take a long time to complete because dependencies need to be built and installed.
Du har ret. :) Jeg har skrevet det lidt uklart.

2022-02-23 14:49 UTC, lurilandi requested changes

2022-02-23 14:49 UTC, lurilandi commented on docker_how_to_run.md
> +The first time you run these docker commands will likely take a long time to complete because dependencies need to be built and installed.
these docker commands? Hvilke commands? Hvorfor skriver du ikke bare "the first time you built an image" eller noget lignende?

2022-02-23 15:40 UTC, lurilandi approved these changes

2022-02-24 11:14 UTC, merged