GIS converter
aarhusstadsarkiv/convertool pull request #424
Opened 2022-03-07 13:17 UTC by Raduq99

Converter for GIS files. Adds a new preprocessing step, i.e. identifying GIS files and grouping them into their corresponding projects.

2022-03-10 07:58 UTC, lurilandi requested changes

2022-03-10 07:58 UTC, lurilandi commented on convertool/cli.py
> +        except Exception as e:
Do you know if identify_gis throws any other exceptions than the base Exception. If so, catch these before you catch the general base Exception.

2022-03-10 07:58 UTC, lurilandi commented on convertool/core/gis_identifier.py
> +    bulkSize = 50
You should probably define `bulkSize` after line 20, so that can use it in `mains = list(processMainFiles(mainFiles))[:bulkSize]`. Also, remember to add a comment on, what the bulkSize is used for. And constants are written in all caps in python, so `bulkSize` should be `BULKSIZE`.

2022-03-10 07:58 UTC, lurilandi commented on convertool/core/gis_identifier.py
> +        )
I find it a bit difficult to understand, what `working_count` is assigned to? I.e. what is the result of:
```Python
            (project_count % bulkSize
            if project_count - i < bulkSize
            else bulkSize)
```

2022-03-10 07:58 UTC, lurilandi commented on convertool/core/gis_identifier.py
> +
A small comment on what happens next would be nice.

2022-03-10 08:14 UTC, clausjuhl approved these changes

2022-03-10 08:59 UTC, lurilandi commented on convertool/cli.py
> +    print("HELLO")
Seems like this was only used for debugging.

2022-04-04 14:38 UTC, lurilandi requested changes

2022-04-04 14:38 UTC, lurilandi commented on convertool/core/gis_processing.py
> +    )
I am not sure that this template text is correct. Claus will need to look at it.

2022-04-04 14:38 UTC, lurilandi commented on tests/conftest.py
> +
I thought this  was already on master. I will look into it.

2022-04-05 08:18 UTC, clausjuhl commented on convertool/core/gis_processing.py
> +    )
```suggestion
    placeholder = (
        "Denne fil er en del af et GIS-projekt "
        "bestående af flere"
        "\nsammenhængende filer), og er blevet "
        "konverteret sammen\nmed de tilhørende "
        f"dokumenter på denne sti:\n{newFile.parent.parent.name}"
        f"/{newFile.parent.name}."
    )
```

2022-04-05 11:28 UTC, lurilandi commented on tests/conftest.py
> +
On master, this fixture is replaced with the `db_conn_tiff_converter` fixture, which is used in both `test_statutory_succes` and `test_tiff_convert_invalid_file_format` in test_statutory.py. I will see what fixture is used on this branch.

2022-04-12 11:11 UTC, lurilandi commented on tests/test_data/gis_test/gis_sample.json
> +        "1": [
Can a key not be an integer in json?

2022-04-12 11:41 UTC, lurilandi commented on convertool/database/file_db.py
> +        self, files: List[Tuple[str, str]], avDb: ArchiveDB
Why is each file a tuple? What does it include? Also, you do access the second element of the tuple?

2022-04-13 07:30 UTC, Raduq99 commented on convertool/cli.py
> +    """Run the gis preprocessing step and runs the identifying step
The way I thought about it was preprocessing = identifying + moving

2022-04-13 07:42 UTC, Raduq99 commented on convertool/core/gis_processing.py
> +                Path(PureWindowsPath(file)) for file in files if Path(file).suffix in AUX_EXTENSIONS
Because I was running this on Ubuntu, a windows path wrapped in Path would use the implementation from PosixPath instead of WindowsPath. This leads to behaviour like:  `parent\file.extension` is file `parent\file.extension` in directory `.`, instead of file "file.extension" in directory `parent`

2022-04-13 08:04 UTC, Raduq99 commented on convertool/database/file_db.py
> +        main_lambda: Any = lambda extension: self.files.c.relative_path.contains(extension)
I agree with your point and indeed a named function is a better idea. The way I ended up declaring and initializing the lambda functions was because Mypy complained about not knowing what is their return type, so I had to infer it in some way and this is the only way I found you could do it in Python (of course `Any` is not that helpful but I just wanted to pass the Mypy checks).

2022-04-13 08:29 UTC, Raduq99 commented on convertool/database/file_db.py
> +            lambda f: path.contains("\\" + Path(f).stem.split("\\")[-1] + "."),
This can happen due to the behaviour of Path mentioned in a comment above, which indeed makes Path useless in this situation. I added some more clarification as to why the substring is of this form

2022-04-13 08:45 UTC, Raduq99 commented on tests/test_data/gis_test/gis_sample.json
> +        "1": [
Keys in JSON are required to be of [string type](https://www.json.org/json-en.html).

2022-04-13 09:14 UTC, Raduq99 commented on convertool/database/file_db.py
> +        self, files: List[Tuple[str, str]], avDb: ArchiveDB
Each tuple is (filename, checksum) and indeed the checksum is not used in this function (not anymore). I will modify it such that it gets only a list of filenames

2022-04-13 09:29 UTC, Raduq99 commented on convertool/core/gis_processing.py
> +    return projects
It is much easier to parse to and from JSON files using `dict` (aka `Mapping`) and operations are a lot faster compared to having a list of objects. Indeed I could trade that to making a new datatype if you feel like it is the case. Or I could add some more documentation, especially since an example of how `Mapping[str, Mapping[str, List[str]]]` looks like is the JSON file that is created.

2022-04-20 07:55 UTC, lurilandi commented on convertool/core/gis_processing.py
> +    return projects
Yes, you have a good point and I agree. Adding some documentation with and example of `Mapping[str, Mapping[str, List[str]]]` would be a good thing.

2022-04-20 08:13 UTC, lurilandi requested changes
Looks great. If you look into my latest comment and add the documentation for the mapping type, it should be ready to merge after another review.

2022-04-20 08:13 UTC, lurilandi commented on convertool/core/gis_processing.py
> +    filenames: List[str] = [file[0] for file in gis_files]
Could you not do `gis_files = list(set(map(lambda f: f[0], files)))` instead of creating the tuples and then extract the first element of each tuple?

2022-04-25 14:11 UTC, lurilandi approved these changes

2022-04-26 11:36 UTC, merged