Cad converter
aarhusstadsarkiv/convertool pull request #431
Opened 2022-04-11 07:47 UTC by felix0908

Since ABViewer is proprietary, I've added a flag to our Pytest setup - any tests that use the cad converter only run when the --cad option is provided.

Also, the cad converter itself doesn't attempt to convert files unless ABViewer is a known command - which I test by checking whether shutil.which("ABViewer") returns a path

2022-04-26 11:34 UTC, lurilandi requested changes
Det ser rigtig fint ud. Jeg har kun nogle små rettelser og kommentare.

2022-04-26 11:34 UTC, lurilandi commented on tests/core/test_cad.py
> +        # Making sure the case where ABViewer isn't installed behaves correctly
Hvad mener du med correctly? Altså hvad er correctly i dette tilfælde?

2022-04-26 11:34 UTC, lurilandi commented on tests/core/test_convert.py
> +
Denne db bliver ikke kopieret i fixturen. Er du sikker på, at den ikke står som ændret af git, når du kører testen?

2022-04-26 11:34 UTC, lurilandi commented on tests/core/test_convert.py
> +    # test might take too long!
Forklar gerne hvorfor.

2022-04-29 07:23 UTC, felix0908 commented on tests/core/test_cad.py
> +        # Making sure the case where ABViewer isn't installed behaves correctly
Det burde nok være uddybet en smule mere, men basically det jeg tester er at det er den specifikke exception (CADSubprocessExecutionError) der bliver raised, i stedet for CADConversionError

2022-04-29 07:25 UTC, felix0908 commented on tests/core/test_cad.py
> +        # Making sure the case where ABViewer isn't installed behaves correctly
Men det er måske egentlig ikke nødvendigt at have det tjek, da CAD converteren ikke burde blive kaldt i det tilfælde.

2022-04-29 07:27 UTC, felix0908 commented on tests/core/test_cad.py
> +        exception_occured: bool = False
Okay, det er handy at vide, tak! Kan godt ske jeg retter det, for jeg var ikke selv super tilfreds med strukturen her

2022-04-29 07:33 UTC, felix0908 commented on tests/core/test_convert.py
> +    # test might take too long!
Well, CAD converteren er ikke super hurtig, og her bliver den bedt om at lave 5 converteringer (3 filer, men dwg og dxf skal både konverteres til et cad format OG pdf, så i alt 5 kald til ABViewer)

Det er dog ikke et stort problem, specielt fordi testen kun kører hvis man giver --cad flaget

2022-04-29 07:33 UTC, felix0908 commented on tests/core/test_convert.py
> +    # test might take too long!
Nogle af mine kommentarer er henvendt mere til mig selv en noget andet, og nogle gange glemmer jeg at rydde op i dem - det her er nok et af de tilfælde

2022-04-29 10:28 UTC, felix0908 commented on tests/core/test_convert.py
> +
Okay, efter lidt mere research, så kan jeg nu fortælle dig præcis hvorfor den ikke står ændret: den eksisterer slet ikke. Der er slet ikke nogen video_test_root directory, og denne fixture er slet ikke brugt i en eneste test.

Det må være leftover kode fra en tidligere udgave af video testsene, som så ikke er blevet fjernet efter ændringerne

2022-05-11 09:17 UTC, merged