Tiff endian fix
aarhusstadsarkiv/convertool pull request #443
Opened 2022-07-01 13:02 UTC by Magniler

Fixed the endianess, should work with both big and small endianded files

2022-07-01 13:32 UTC, lurilandi requested changes

2022-07-01 13:32 UTC, lurilandi commented on convertool/core/process_tif.py
> +# Gets the lower order two bytes from fields that can fit into this space, no need to look op elsewhere
Well this is not all correct, since you do not return two bytes, but a value that is stored in two bytes.

2022-07-01 13:32 UTC, lurilandi commented on convertool/core/process_tif.py
> +        raise Exception
```suggestion
        raise Exception("Unsupported TIF file")
```

2022-07-01 13:32 UTC, lurilandi commented on convertool/core/process_tif.py
> +from turtle import width
Seems like an unused auto import.

2022-07-04 13:25 UTC, clausjuhl commented on convertool/core/process_tif.py
> +def get_value_offset(bytes: bytes, file_offset: int, byte_ordering: str) -> int:
Missing documentation

2022-07-04 13:25 UTC, clausjuhl commented on convertool/core/process_tif.py
> +def parse_tif_long_field(bytes: bytes, value_offset: int, byte_ordering: str) -> int:
Missing documentation

2022-07-04 13:32 UTC, clausjuhl commented on convertool/core/converters/image.py
> +    if image_info["X_RESOLUTION"] > image_info["Y_RESOLUTION"]:
Add logic to handle instances of missing keys

2022-07-04 13:36 UTC, clausjuhl commented on convertool/core/converters/image.py
> +                if image_object.depth > 2:
```suggestion
                if image_object.depth > 1:
```

2022-08-08 11:33 UTC, lurilandi requested changes

2022-08-08 11:33 UTC, lurilandi commented on tests/core/test_image.py
> +        file_path: str = root_images_path + name_of_file
Why not use a fixture to test_tiff_images along with pathlib instead of using strings and string concatination?

2022-08-09 13:19 UTC, Magniler reviewed
Responded to requests, pushing new version soon

2022-09-02 11:52 UTC, lurilandi approved these changes

2022-09-12 07:50 UTC, clausjuhl approved these changes

2022-09-12 13:26 UTC, clausjuhl approved these changes

2022-09-12 13:26 UTC, merged